name: Update lockfiles

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
#   schedule:
#     - cron: "0 0 1 * *"  # monthly

jobs:
  pixi-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.14
        with:
          run-install: false

      - name: Update lockfiles
        run: |
          set -o pipefail
          pixi update --json --no-install | pixi exec pixi-diff-to-markdown >> diff.md

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "bump: update pixi lockfile"
          title: "bump: update pixi lockfile"
          body-path: diff.md
          branch: update-pixi
          base: main
          labels: pixi,chore
          delete-branch: true
          add-paths: pixi.lock
